### ISSUE TITLE
Readme symbols not translating on .io

### ISSUE THREAD

**Issue by trashbirdecology** [EcologicalTraitData/traitdataform#37]
An FYI, for some reason the apostrophes (') at the first header of your README (Package 'traitdataform') are not translating correctly to [your .io landing page](https://ecologicaltraitdata.github.io/traitdataform/#package-traitdataform-formatting-and-harmonizing-ecological-trait-data).

The apostrophes are showing up for me (Chrome Browser, English language) as " â"

**Comment by fdschneider** [comment]
strange. it also messes up all commas. Those pages are auto-generated by the 'pkgdown' package.  I hope it will be fixed automatically with the next push. Thanks.

**Comment by trashbirdecology** [comment]
Maybe check/submit a PR over at pkgdown?

*______________________________________________________*

Jessica L. Burnett (she/her)

Mendenhall Postdoctoral Fellow & Research Ecologist

US Geological Survey Science Analytics and Synthesis
<https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis>

Github <http://github.com/trashbirdecology>

ORCID: 0000-0002-0896-5099
<https://orcid.org/0000-0002-0896-5099>
*______________________________________________________*


Join the Community for Data Integration <https://www.usgs.gov/centers/cdi>! All
welcome. It's cool.

**Comment by fdschneider** [comment]
Has been fixed by moving pkdown deploy to the much more elegant Github Actions (the Travis-CI deploy routine was out-dated, [see ROpenSci Labs on this topic](https://ropenscilabs.github.io/actions_sandbox/websites-using-pkgdown-bookdown-and-blogdown.html))

**Comment by trashbirdecology** [comment]
oh, nice find
