### ISSUE TITLE
Very Minor: documentation error for get_gbif_taxonomy

### ISSUE THREAD

**Issue by mikeroswell** [EcologicalTraitData/traitdataform#38]
Hi,
This hardly deserves an "issue" but noticed that `get_gbif_taxonomy` documentation says that the default is `fuzzy = FALSE` but I think the code as written has the default as `fuzzy = TRUE`. Should be a quick fix when you next update :-)

**Comment by fdschneider** [comment]
Thanks! I updated the documentation, as fuzzy matching is indeed the default behaviour for dealing with misspelled taxon names. In rare cases, fuzzy matching also leads to wrong taxon assignments.
