### ISSUE TITLE
include datasets for testing 

### ISSUE THREAD

**Issue by fdschneider** [EcologicalTraitData/traitdataform#47]
Since the reference to the external trait datasets on Dryad and other sources are not stable enough, a next version should include the raw data in the package. This would include
- arthropodtraits
- heteroptera
- heteroptera_raw
- carabids

probably the other demo data would be removed to minimize these issues.  Ideally, recipes for pulling datasets from published trait data (e.g. pantheria #43) would be provided elsewhere, e.g. through the [Open Traits Network](https://opentraits.org).

**Comment by fdschneider** [comment]
@willpearse 
You suggested to use the [suppdata](https://github.com/ropensci/suppdata) package to download the data with more stable references. That seems like the way to go.  
Could you also give some example for the caching procedure you mentioned to keep CRAN calm.

**Comment by willpearse** [comment]
No worries! It's in SymbiotaR2 (https://github.com/ropensci/SymbiotaR2) and
is the 'casette' package. It is perhaps fractionally fiddly to set up the
first time, but then it 'just works' and is wonderful, genuinely.

>

**Comment by fdschneider** [comment]
Thanks, I solved this for now by including the small demo data into the package for offline availability and I exchanged some of the data downloads with suppdata calls. However, since two of the datasets are on esa archives, this was not available. I did not apply casette caching for now. But this might be usefull to wrap around repeated taxize calls.
